### VÁLTOZÓK
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
@token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef
### LOGIN
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "vasarlo1@example.com",
    "password": "ronaldo"
}

### TOKEN FRISSÍTÉSE
# @token = {{login.response.body.data.token}}

### LOGOUT USER
POST {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}

### GET ALL USERS
GET {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get all species
GET http://localhost:8000/api/specie
Accept: application/json
Authorization: Bearer {{token}}


### GET USER BY ID
GET {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### CREATE NEW USER
POST {{host}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "Vásárló2",
    "email": "vasarlo2@example.com",
    "password": "123"
}

### UPDATE USER
PATCH {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "No Boss"
}

### DELETE USER
DELETE {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### DELETE SELF
DELETE {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### UPDATE SELF INFO
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "vasarlo2",
    "email": "vasarlo2@example.com"
}

### SELF PATCH ROLE (TILTOTT)
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "admin1"
}

### SELF PASSWORD CHANGE
PATCH {{host}}/api/usersmeupdatepassword
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "oldpassword": "ronaldo",
    "newpassword": "123",
    "newpassword_confirmation": "123"
}

### GET SELF INFO
GET {{host}}/api/usersme
Accept: application/json
Authorization: Bearer {{token}}

### TESZT ENDPOINT
GET {{host}}/api/x

### GET ALL PRODUCTS
GET {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### GET PRODUCT BY ID
GET {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE PRODUCT
POST {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "Bogyós",
    "name": "f3333xx",
    "description": "Kézzel termelt egészség",
    "picture": "https://hur.webmania.cc/img/malna.jpg",
    "price": 8000,
    "stock": 22
}

### DELETE PRODUCT BY ID
DELETE {{host}}/api/products/104
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH PRODUCT
PATCH {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "price": 1002,
    "stock": "eee"
}
